# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        babel-eslint: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: |
        yarn install
        yarn add -D babel-eslint@${{ matrix.babel-eslint }}
    - run: yarn add -D escope
      if: matrix.babel-eslint <= 6
    - run: yarn add -D estraverse-fb
      if: matrix.babel-eslint == 4
    - run: yarn test
